/* Pulls current Drilling and Completions operations from Offshore
David C. Garza 01/03/2017. Updated the DTTMSTART date to pull current date automatically. */

USE wv101CalcUnitsUS

SELECT WVWELLHEADER.DISTRICT, WVJOB.jobtyp AS 'Job Type', WVWELLHEADER.WELLNAME AS 'Well Name' 
FROM WVWELLHEADER JOIN WVJOB ON WVWELLHEADER.IDWELL = WVJOB.IDWELL 
JOIN WVJOBREPORT ON WVJOBREPORT.IDRECPARENT = WVJOB.IDREC
 WHERE 
	WVJOBREPORT.DTTMSTART =  CAST(GETDATE() AS date)
	AND WVWELLHEADER.LOCATIONTYP = 'Offshore'
	AND (WVJOB.JOBTYP = 'Drilling' OR WVJOB.JOBTYP = 'Completion')
	AND WVWELLHEADER.OPERATOR = 'Hess Corporation'
 ORDER BY WVWELLHEADER.DISTRICT, WVJOB.JOBTYP DESC