/* Pulls the time long for a given asset. List the job type, well name, rig, start date and time of time block, NPT of the block, and duration of the block.
David C. Garza 02/01/2018 */

USE wv101CalcUnitsUS

DECLARE	@startdate AS DATE
DECLARE @enddate AS DATE
DECLARE @Asset AS CHAR(20)
SET @startdate  = '2016-01-01'
SET @enddate = '2018-01-01'
SET @Asset = 'GOM Deepwater'

SELECT WVJOB.jobtyp AS 'Job Type', WVWELLHEADER.WELLNAME AS 'Well Name',  WVJOBRIG.RIGNO AS 'Rig', WVJOBREPORTTIMELOG.DTTMSTARTCALC AS 'Start Date and Time', WVJOBREPORTTIMELOG.UNSCHEDTYP AS 'NPT Code',  WVJOBREPORTTIMELOG.DURATION AS 'Duration'
FROM WVWELLHEADER
JOIN WVJOB ON WVWELLHEADER.IDWELL = WVJOB.IDWELL 
JOIN WVJOBREPORT ON WVJOBREPORT.IDRECPARENT = WVJOB.IDREC
JOIN WVJOBREPORTTIMELOG ON WVJOBREPORT.IDREC = WVJOBREPORTTIMELOG.IDRECPARENT
JOIN WVJOBRIG ON WVJOBREPORTTIMELOG.IDRECLASTRIGCALC = WVJOBRIG.IDREC
WHERE 
	WVJOBREPORTTIMELOG.DTTMSTARTCALC >= @startdate 
	AND WVJOBREPORTTIMELOG.DTTMSTARTCALC < @enddate
	AND WVWELLHEADER.DISTRICT = @Asset
	AND WVWELLHEADER.OPERATOR = 'Hess Corporation'
 ORDER BY WVWELLHEADER.WELLNAME ASC, WVJOB.jobtyp ASC, WVJOBREPORTTIMELOG.DTTMSTARTCALC ASC